# Generated by Django 4.2.6 on 2023-11-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clientmodel_remote_host'),
        ('chat', '0002_chatmodel_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientmodel'),
        ),
    ]
