# Generated by Django 4.2.6 on 2023-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmodel_question_alter_chatmodel_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='new_conversation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
