# Generated by Django 4.2.6 on 2023-12-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmodel_new_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='question',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='response',
            field=models.CharField(max_length=2000),
        ),
    ]
