# Generated by Django 4.2.6 on 2023-11-02 18:42

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documentmodel_delete_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('../../uploads')),
        ),
    ]
