# Generated by Django 4.2.6 on 2023-11-10 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_alter_documentmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
