version: "3.8"

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./dcb_frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dcb_frontend
    networks:
      - frontend_network

  dcb_frontend:
    container_name: dcb_frontend
    build:
      context: /dcb_frontend/.
    image: dcb_frontend
    env_file:
      - "./dcb_frontend/.env.local"
    command: ["npm", "start"]
    networks:
      - frontend_network

networks:
  frontend_network: