version: "3.8"

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - data:/app
    depends_on:
      - dcb_frontend

  dcb_frontend:
    container_name: dcb_frontend
    build:
      context: .
    image: dcb_frontend
    ports:
      - 3000:3000
    env_file:
      - ".env.local"