version: "3.8"

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dcb_frontend
    networks:
      - dcb_frontend_network

  dcb_frontend:
    container_name: dcb_frontend
    build:
      context: .
    image: dcb_frontend
    env_file:
      - ".env.production"
    command: ["npm", "start"]
    networks:
      - dcb_frontend_network

networks:
  dcb_frontend_network: