version: "3.8"

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: "nginx"
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - dcb_frontend
    networks:
      - dcb_frontend_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTBOT_EMAIL} -d ${DOMAIN} --agree-tos

  dcb_frontend:
    container_name: dcb_frontend
    build:
      context: .
    image: dcb_frontend
    env_file:
      - ".env.production"
    command: ["npm", "start"]
    networks:
      - dcb_frontend_network

networks:
  dcb_frontend_network: