version: "3.8"

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: "nginx_backend"
    ports:
      - 88:88
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dcb_backend
    networks:
      - dcb_backend_network

  dcb_backend:
    build:
      context: .
    image: dcb_backend
    container_name: "dcb_backend"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - ".env"
    volumes:
      - vectorstore:/app/VECTORSTORE
      - uploads:/app/uploads
    depends_on:
      - database
      - redis
    networks:
      - dcb_backend_network
  
  database:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ".env"
    environment:
      - POSTGRES_NAME=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
    networks:
      - dcb_backend_network

  redis:
    image: 'redis/redis-stack-server:7.2.0-v6'
    expose:
      - "6379"
    networks:
      - dcb_backend_network


volumes:
  uploads:
  vectorstore:
  database:

networks:
  dcb_backend_network: