version: "3.8"

services:

  dcb_backend:
    build:
      context: .
    image: dcb_backend
    container_name: "dcb_backend"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ".env"
    volumes:
      - data:/app
    depends_on:
      - redis
      - database
  
  database:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ".env"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: 'redis/redis-stack-server'
    ports:
    - '6379:6379'

volumes:
  data: