# Generated by Django 4.2.6 on 2023-11-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clientmodel_remote_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='session_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
